[package]
name = "pyenv-shim"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[[bin]]
name = "pyenv-shim"
path = "src/main.rs"

[dependencies]
rpyenv-core.workspace = true

[target.'cfg(windows)'.dev-dependencies]
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_System_LibraryLoader"] }
